trigger: none
pr:
  - main

pool:
  name: AppTest Debian
  demands: Agent.OS -equals Linux

resources:
  repositories:
    - repository: PipelineTemplates
      type: git
      name: CyberLab-Services/pipeline-templates
      ref: refs/heads/main
      trigger: none
    # update container image reference
    - repository: azul-app-azure
      type: git
      name: Azul/azul-app-azure
      ref: refs/heads/main
      trigger: none
  pipelines:
    - pipeline: azul-bedrock
      source: ag-release-dev\ag-azul-bedrock-release-dev
      project: Azul
      trigger: true

extends:
  template: v2/stages/test-build-publish.yaml@PipelineTemplates
  parameters:
    is_dev: true
    is_golang: true
    is_docker: true
    is_deploy: true
    deploy_subdir: azul-dev