package handlersv3

import (
	bh "github.com/AustralianCyberSecurityCentre/azul-plugin-virustotal.git/virustotal/vtmap/basehandlerv3"
)

var vtToAzFeatDotNetGuids = []bh.VtPathToAzFeature{
	bh.NewVtPathToAzFeat("mvid", bh.VtTypeString, "mvid", bh.AzFTString, "dotNetGuids - ModuleVersionID, generated at build time, resulting in a new GUID for each build."),
	bh.NewVtPathToAzFeat("typelib_id", bh.VtTypeString, "typelib_id", bh.AzFTString, "dotNetGuids - TypeLib ID (if present), generated by Visual Studio on the creation of a new project by default."),
}

var DotNetGuids = bh.NewHandlerV3(vtToAzFeatDotNetGuids, "dot_net_guids")
